---
- name: Install pip
  shell: "easy_install pip"
  become: true

- name: Install virtualenv
  pip:
    name: virtualenv
    state: latest
    executable: /usr/local/bin/pip
  become: true

- name: Setup python virtualenv for the test suite
  command: "./setup_python.sh /Users/{{xv_leak_test_user}}/xv_leak_test_python"
  args:
    chdir: "{{ xv_leak_testing_directory }}"
